// adTemplates.js — 12 production-quality banner ad templates
// Each template defines a complete layoutConfig + buttonStyle that transforms
// the banner into a distinct professional visual style.
// Admin selects a template → all layout/button fields update instantly in the preview.

export const AD_TEMPLATES = [
  {
    id: "bold-dark",
    name: "Bold Dark",
    category: "Premium",
    description: "High-contrast dark overlay, large title, filled white button",
    preview: {
      bg: "#09090b",
      accent: "#ffffff",
      badge: "#6366f1",
    },
    layoutConfig: {
      textPosition:     "bl",
      overlayDirection: "to-top",
      overlayOpacity:   88,
      overlayColor:     "#040408",
      titleSize:        "xl",
      titleWeight:      "black",
      titleColor:       "#ffffff",
      descColor:        "rgba(212,212,216,0.8)",
      showBadge:        true,
      showSponsorTag:   true,
      showDescription:  true,
      showProgressBar:  true,
      showDetailsBtn:   true,
      showMuteBtn:      true,
      slideDuration:    5000,
      badgeText:        "",
      badgeColor:       "rgba(99,102,241,0.9)",
    },
    buttonStyle: {
      variant:      "filled",
      bgColor:      "#ffffff",
      textColor:    "#000000",
      borderColor:  "#ffffff",
      radius:       "md",
      icon:         "arrow",
      iconPosition: "right",
    },
  },

  {
    id: "cinematic",
    name: "Cinematic",
    category: "Premium",
    description: "Left-to-right dark fade, centered title, ghost button",
    preview: {
      bg: "#1a0a00",
      accent: "#f59e0b",
      badge: "#f59e0b",
    },
    layoutConfig: {
      textPosition:     "ml",
      overlayDirection: "to-right",
      overlayOpacity:   90,
      overlayColor:     "#0a0500",
      titleSize:        "lg",
      titleWeight:      "black",
      titleColor:       "#fff7ed",
      descColor:        "rgba(253,230,138,0.75)",
      showBadge:        true,
      showSponsorTag:   false,
      showDescription:  true,
      showProgressBar:  false,
      showDetailsBtn:   false,
      showMuteBtn:      true,
      slideDuration:    7000,
      badgeText:        "FEATURED",
      badgeColor:       "rgba(245,158,11,0.85)",
    },
    buttonStyle: {
      variant:      "ghost",
      bgColor:      "#f59e0b",
      textColor:    "#ffffff",
      borderColor:  "rgba(245,158,11,0.6)",
      radius:       "full",
      icon:         "chevron",
      iconPosition: "right",
    },
  },

  {
    id: "neon-glow",
    name: "Neon Glow",
    category: "Bold",
    description: "Deep purple overlay, bright badge, outline button",
    preview: {
      bg: "#0d0019",
      accent: "#a855f7",
      badge: "#a855f7",
    },
    layoutConfig: {
      textPosition:     "bc",
      overlayDirection: "radial",
      overlayOpacity:   82,
      overlayColor:     "#0d0019",
      titleSize:        "lg",
      titleWeight:      "black",
      titleColor:       "#f3e8ff",
      descColor:        "rgba(196,181,253,0.8)",
      showBadge:        true,
      showSponsorTag:   true,
      showDescription:  true,
      showProgressBar:  true,
      showDetailsBtn:   true,
      showMuteBtn:      true,
      slideDuration:    5000,
      badgeText:        "SPONSOR",
      badgeColor:       "rgba(168,85,247,0.85)",
    },
    buttonStyle: {
      variant:      "outline",
      bgColor:      "#a855f7",
      textColor:    "#f3e8ff",
      borderColor:  "#a855f7",
      radius:       "full",
      icon:         "arrow",
      iconPosition: "right",
    },
  },

  {
    id: "minimal-white",
    name: "Minimal White",
    category: "Clean",
    description: "Subtle bottom fade, small title, clean pill button",
    preview: {
      bg: "#f8fafc",
      accent: "#0f172a",
      badge: "#0f172a",
    },
    layoutConfig: {
      textPosition:     "bl",
      overlayDirection: "to-top",
      overlayOpacity:   60,
      overlayColor:     "#ffffff",
      titleSize:        "md",
      titleWeight:      "bold",
      titleColor:       "#0f172a",
      descColor:        "rgba(30,41,59,0.7)",
      showBadge:        false,
      showSponsorTag:   false,
      showDescription:  true,
      showProgressBar:  true,
      showDetailsBtn:   false,
      showMuteBtn:      true,
      slideDuration:    6000,
      badgeText:        "",
      badgeColor:       "rgba(15,23,42,0.1)",
    },
    buttonStyle: {
      variant:      "filled",
      bgColor:      "#0f172a",
      textColor:    "#ffffff",
      borderColor:  "#0f172a",
      radius:       "full",
      icon:         "chevron",
      iconPosition: "right",
    },
  },

  {
    id: "emerald-brand",
    name: "Emerald Brand",
    category: "Brand",
    description: "Strong emerald badge, right-side fade, rounded button",
    preview: {
      bg: "#022c22",
      accent: "#10b981",
      badge: "#10b981",
    },
    layoutConfig: {
      textPosition:     "bl",
      overlayDirection: "to-top",
      overlayOpacity:   85,
      overlayColor:     "#022c22",
      titleSize:        "lg",
      titleWeight:      "extrabold",
      titleColor:       "#ecfdf5",
      descColor:        "rgba(167,243,208,0.8)",
      showBadge:        true,
      showSponsorTag:   false,
      showDescription:  true,
      showProgressBar:  true,
      showDetailsBtn:   true,
      showMuteBtn:      true,
      slideDuration:    5000,
      badgeText:        "NEW",
      badgeColor:       "rgba(16,185,129,0.9)",
    },
    buttonStyle: {
      variant:      "filled",
      bgColor:      "#10b981",
      textColor:    "#022c22",
      borderColor:  "#10b981",
      radius:       "lg",
      icon:         "arrow",
      iconPosition: "right",
    },
  },

  {
    id: "sunset-warm",
    name: "Sunset Warm",
    category: "Bold",
    description: "Warm orange/amber palette, top-left title, globe button",
    preview: {
      bg: "#431407",
      accent: "#fb923c",
      badge: "#fb923c",
    },
    layoutConfig: {
      textPosition:     "tl",
      overlayDirection: "to-bottom",
      overlayOpacity:   78,
      overlayColor:     "#431407",
      titleSize:        "lg",
      titleWeight:      "black",
      titleColor:       "#fff7ed",
      descColor:        "rgba(254,215,170,0.85)",
      showBadge:        true,
      showSponsorTag:   true,
      showDescription:  true,
      showProgressBar:  false,
      showDetailsBtn:   false,
      showMuteBtn:      true,
      slideDuration:    5500,
      badgeText:        "HOT",
      badgeColor:       "rgba(251,146,60,0.9)",
    },
    buttonStyle: {
      variant:      "filled",
      bgColor:      "#fb923c",
      textColor:    "#431407",
      borderColor:  "#fb923c",
      radius:       "md",
      icon:         "globe",
      iconPosition: "right",
    },
  },

  {
    id: "ocean-blue",
    name: "Ocean Blue",
    category: "Clean",
    description: "Deep blue overlay, centered layout, outline pill button",
    preview: {
      bg: "#0c1445",
      accent: "#60a5fa",
      badge: "#60a5fa",
    },
    layoutConfig: {
      textPosition:     "mc",
      overlayDirection: "radial",
      overlayOpacity:   80,
      overlayColor:     "#0c1445",
      titleSize:        "xl",
      titleWeight:      "black",
      titleColor:       "#eff6ff",
      descColor:        "rgba(147,197,253,0.8)",
      showBadge:        true,
      showSponsorTag:   false,
      showDescription:  true,
      showProgressBar:  true,
      showDetailsBtn:   true,
      showMuteBtn:      true,
      slideDuration:    6000,
      badgeText:        "SPONSOR",
      badgeColor:       "rgba(59,130,246,0.85)",
    },
    buttonStyle: {
      variant:      "outline",
      bgColor:      "#3b82f6",
      textColor:    "#eff6ff",
      borderColor:  "#93c5fd",
      radius:       "full",
      icon:         "arrow",
      iconPosition: "right",
    },
  },

  {
    id: "rose-luxury",
    name: "Rose Luxury",
    category: "Premium",
    description: "Rose-pink palette, right-aligned text, Instagram button",
    preview: {
      bg: "#4c0519",
      accent: "#fb7185",
      badge: "#fb7185",
    },
    layoutConfig: {
      textPosition:     "br",
      overlayDirection: "to-left",
      overlayOpacity:   85,
      overlayColor:     "#4c0519",
      titleSize:        "md",
      titleWeight:      "black",
      titleColor:       "#fff1f2",
      descColor:        "rgba(254,205,211,0.8)",
      showBadge:        true,
      showSponsorTag:   true,
      showDescription:  true,
      showProgressBar:  false,
      showDetailsBtn:   false,
      showMuteBtn:      true,
      slideDuration:    5000,
      badgeText:        "EXCLUSIVE",
      badgeColor:       "rgba(251,113,133,0.9)",
    },
    buttonStyle: {
      variant:      "filled",
      bgColor:      "#fb7185",
      textColor:    "#4c0519",
      borderColor:  "#fb7185",
      radius:       "full",
      icon:         "instagram",
      iconPosition: "right",
    },
  },

  {
    id: "corporate-steel",
    name: "Corporate Steel",
    category: "Professional",
    description: "Neutral grey, no-overlay clean look, sharp corners",
    preview: {
      bg: "#1c1917",
      accent: "#a8a29e",
      badge: "#78716c",
    },
    layoutConfig: {
      textPosition:     "bl",
      overlayDirection: "to-top",
      overlayOpacity:   70,
      overlayColor:     "#1c1917",
      titleSize:        "md",
      titleWeight:      "extrabold",
      titleColor:       "#fafaf9",
      descColor:        "rgba(214,211,209,0.75)",
      showBadge:        true,
      showSponsorTag:   false,
      showDescription:  true,
      showProgressBar:  true,
      showDetailsBtn:   true,
      showMuteBtn:      true,
      slideDuration:    5000,
      badgeText:        "AD",
      badgeColor:       "rgba(120,113,108,0.85)",
    },
    buttonStyle: {
      variant:      "filled",
      bgColor:      "#fafaf9",
      textColor:    "#1c1917",
      borderColor:  "#fafaf9",
      radius:       "sm",
      icon:         "chevron",
      iconPosition: "right",
    },
  },

  {
    id: "midnight-gold",
    name: "Midnight Gold",
    category: "Premium",
    description: "Dark background, gold accent badge, top-right aligned",
    preview: {
      bg: "#0a0700",
      accent: "#d97706",
      badge: "#d97706",
    },
    layoutConfig: {
      textPosition:     "tr",
      overlayDirection: "to-left",
      overlayOpacity:   80,
      overlayColor:     "#0a0700",
      titleSize:        "lg",
      titleWeight:      "black",
      titleColor:       "#fef9c3",
      descColor:        "rgba(253,224,71,0.7)",
      showBadge:        true,
      showSponsorTag:   false,
      showDescription:  true,
      showProgressBar:  false,
      showDetailsBtn:   true,
      showMuteBtn:      true,
      slideDuration:    6500,
      badgeText:        "PREMIUM",
      badgeColor:       "rgba(217,119,6,0.9)",
    },
    buttonStyle: {
      variant:      "outline",
      bgColor:      "#d97706",
      textColor:    "#fef9c3",
      borderColor:  "#d97706",
      radius:       "md",
      icon:         "globe",
      iconPosition: "left",
    },
  },

  {
    id: "tech-minimal",
    name: "Tech Minimal",
    category: "Professional",
    description: "No overlay, bottom-centered, ghost button with none icon",
    preview: {
      bg: "#030712",
      accent: "#22d3ee",
      badge: "#22d3ee",
    },
    layoutConfig: {
      textPosition:     "bc",
      overlayDirection: "to-top",
      overlayOpacity:   65,
      overlayColor:     "#030712",
      titleSize:        "md",
      titleWeight:      "bold",
      titleColor:       "#e0f2fe",
      descColor:        "rgba(125,211,252,0.8)",
      showBadge:        true,
      showSponsorTag:   false,
      showDescription:  true,
      showProgressBar:  true,
      showDetailsBtn:   false,
      showMuteBtn:      true,
      slideDuration:    4500,
      badgeText:        "TECH",
      badgeColor:       "rgba(6,182,212,0.85)",
    },
    buttonStyle: {
      variant:      "ghost",
      bgColor:      "#22d3ee",
      textColor:    "#e0f2fe",
      borderColor:  "rgba(34,211,238,0.5)",
      radius:       "lg",
      icon:         "arrow",
      iconPosition: "right",
    },
  },

  {
    id: "vivid-split",
    name: "Vivid Split",
    category: "Bold",
    description: "Left-aligned title, strong colour band, no progress bar",
    preview: {
      bg: "#14002a",
      accent: "#c084fc",
      badge: "#c084fc",
    },
    layoutConfig: {
      textPosition:     "ml",
      overlayDirection: "to-right",
      overlayOpacity:   92,
      overlayColor:     "#14002a",
      titleSize:        "xl",
      titleWeight:      "black",
      titleColor:       "#faf5ff",
      descColor:        "rgba(233,213,255,0.75)",
      showBadge:        true,
      showSponsorTag:   true,
      showDescription:  true,
      showProgressBar:  false,
      showDetailsBtn:   true,
      showMuteBtn:      true,
      slideDuration:    5000,
      badgeText:        "",
      badgeColor:       "rgba(192,132,252,0.85)",
    },
    buttonStyle: {
      variant:      "filled",
      bgColor:      "#c084fc",
      textColor:    "#14002a",
      borderColor:  "#c084fc",
      radius:       "full",
      icon:         "chevron",
      iconPosition: "right",
    },
  },
];

// Category colors for filter pills
export const TEMPLATE_CATEGORIES = {
  "All":          { bg: "rgba(99,102,241,0.15)",  color: "#818cf8", border: "#6366f1" },
  "Premium":      { bg: "rgba(217,119,6,0.15)",   color: "#fbbf24", border: "#d97706" },
  "Bold":         { bg: "rgba(239,68,68,0.15)",   color: "#f87171", border: "#ef4444" },
  "Clean":        { bg: "rgba(16,185,129,0.15)",  color: "#34d399", border: "#10b981" },
  "Professional": { bg: "rgba(148,163,184,0.15)", color: "#94a3b8", border: "#64748b" },
  "Brand":        { bg: "rgba(59,130,246,0.15)",  color: "#60a5fa", border: "#3b82f6" },
};