package com.suvix.payment.domain.payment.webhook;

public enum NormalizedEventType {
    SUBSCRIPTION_AUTHENTICATED,
    SUBSCRIPTION_ACTIVATED,
    SUBSCRIPTION_CHARGED,
    SUBSCRIPTION_PENDING,
    SUBSCRIPTION_HALTED,
    SUBSCRIPTION_CANCELLED,
    SUBSCRIPTION_PAUSED,
    SUBSCRIPTION_RESUMED,
    PAYMENT_AUTHORIZED,
    PAYMENT_FAILED,
    REFUND_PROCESSED,
    UNKNOWN
}