import type { Template } from '../types/template.types';

/**
 * STARTER_TEMPLATES
 * Curated production templates to give users instant, professional starting points.
 */
export const STARTER_TEMPLATES: Template[] = [
  {
    id: 'creator-basic',
    version: 1,
    name: 'Creator Minimal',
    description: 'Clean aesthetic profile with featured links and social bar',
    category: 'creator',
    thumbnailUrl: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=400&auto=format&fit=crop&q=80',
    isPremium: false,
    isActive: true,
    tags: ['minimal', 'creator', 'popular'],
    defaultBlocks: [
      {
        id: 'block_header_1',
        type: 'profile-header',
        schemaVersion: 1,
        order: 0,
        config: {
          imageUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=300&auto=format&fit=crop&q=80',
          title: 'Sarah Jenkins',
          subtitle: 'Content Creator & Photographer 📸 sharing daily visual stories',
          variant: 'centered',
          alignment: 'center',
          showVerifiedBadge: true,
        },
        isVisible: true,
      },
      {
        id: 'block_social_1',
        type: 'social-bar',
        schemaVersion: 1,
        order: 1,
        config: {
          links: [
            { id: '1', platform: 'instagram', url: 'https://instagram.com' },
            { id: '2', platform: 'youtube', url: 'https://youtube.com' },
            { id: '3', platform: 'twitter', url: 'https://twitter.com' },
            { id: '4', platform: 'spotify', url: 'https://spotify.com' },
          ],
          style: 'icons-only',
          size: 'medium',
          color: '#ffffff',
        },
        isVisible: true,
      },
      {
        id: 'block_link_1',
        type: 'link-button',
        schemaVersion: 1,
        order: 2,
        config: {
          text: 'Watch My Latest YouTube Vlog',
          subtitle: 'Behind the scenes of our Japan trip ✈️',
          url: 'https://youtube.com',
          variant: 'solid',
          color: '#ef4444',
          textColor: '#ffffff',
          icon: 'Play',
          animation: 'pulse',
          openInNewTab: true,
        },
        isVisible: true,
      },
      {
        id: 'block_link_2',
        type: 'link-button',
        schemaVersion: 1,
        order: 3,
        config: {
          text: 'My Lightroom Presets (Summer Edition)',
          subtitle: 'Get the exact colors from my Instagram',
          url: 'https://example.com/presets',
          variant: 'outline',
          color: '#38bdf8',
          textColor: '#ffffff',
          icon: 'Camera',
          animation: 'none',
          openInNewTab: true,
        },
        isVisible: true,
      },
      {
        id: 'block_email_1',
        type: 'email-capture',
        schemaVersion: 1,
        order: 4,
        config: {
          title: 'Join The Creator Weekly',
          subtitle: 'Direct camera settings, gear deals and creative insights.',
          buttonText: 'Subscribe Free',
          successMessage: 'Welcome aboard! Check your email.',
        },
        isVisible: true,
      },
    ],
    defaultTheme: {
      background: {
        type: 'gradient',
        gradient: {
          colors: ['#0f172a', '#1e1b4b', '#0f172a'],
          angle: 135,
          type: 'linear',
        },
      },
      typography: {
        fontFamily: 'Inter',
        headingSize: 'medium',
        bodySize: 'medium',
        headingWeight: 'bold',
      },
      buttons: {
        style: 'rounded',
        shadow: 'medium',
        animation: 'none',
        borderRadius: 14,
      },
      spacing: {
        blockGap: 'comfortable',
        pagePadding: 'medium',
        maxWidth: 'medium',
      },
      colors: {
        primary: '#38bdf8',
        secondary: '#818cf8',
        text: '#f8fafc',
        textMuted: '#94a3b8',
        background: '#0f172a',
        cardBackground: 'rgba(30, 41, 59, 0.7)',
      },
    },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },

  {
    id: 'shop-store',
    version: 1,
    name: 'Shop & Merch Store',
    description: 'Feature bestsellers, discount announcements, and direct checkout links',
    category: 'commerce',
    thumbnailUrl: 'https://images.unsplash.com/photo-1472851294608-062f824d29cc?w=400&auto=format&fit=crop&q=80',
    isPremium: false,
    isActive: true,
    tags: ['store', 'products', 'ecommerce'],
    defaultBlocks: [
      {
        id: 'block_header_store',
        type: 'profile-header',
        schemaVersion: 1,
        order: 0,
        config: {
          imageUrl: 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?w=300&auto=format&fit=crop&q=80',
          title: 'KAI Merch Studio',
          subtitle: 'Limited Edition Streetwear & Creator Accessories ✨',
          variant: 'banner',
          bannerUrl: 'https://images.unsplash.com/photo-1523381210434-271e8be1f52b?w=600&auto=format&fit=crop&q=80',
          alignment: 'center',
          showVerifiedBadge: true,
        },
        isVisible: true,
      },
      {
        id: 'block_countdown_store',
        type: 'countdown',
        schemaVersion: 1,
        order: 1,
        config: {
          title: '🔥 Midnight Cyber Drop Ends In:',
          targetDate: new Date(Date.now() + 4 * 24 * 60 * 60 * 1000).toISOString(),
          expiredText: 'Sale has ended! Stay tuned for next release.',
        },
        isVisible: true,
      },
      {
        id: 'block_products_store',
        type: 'product-grid',
        schemaVersion: 1,
        order: 2,
        config: {
          products: [
            {
              id: 'p1',
              title: 'Heavyweight Oversized Hoodie',
              price: '$68.00',
              imageUrl: 'https://images.unsplash.com/photo-1556905055-8f358a7a47b2?w=300&auto=format&fit=crop&q=80',
              url: 'https://store.example.com/hoodie',
              badge: 'POPULAR',
            },
            {
              id: 'p2',
              title: 'Matte Black Coffee Tumbler',
              price: '$28.00',
              imageUrl: 'https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?w=300&auto=format&fit=crop&q=80',
              url: 'https://store.example.com/tumbler',
            },
          ],
          columns: 2,
          showPrice: true,
        },
        isVisible: true,
      },
      {
        id: 'block_link_store',
        type: 'link-button',
        schemaVersion: 1,
        order: 3,
        config: {
          text: 'Browse Complete Fall Collection',
          subtitle: 'Worldwide express shipping available',
          url: 'https://store.example.com',
          variant: 'solid',
          color: '#10b981',
          textColor: '#ffffff',
          icon: 'ShoppingBag',
          animation: 'glow',
          openInNewTab: true,
        },
        isVisible: true,
      },
    ],
    defaultTheme: {
      background: {
        type: 'solid',
        color: '#111827',
      },
      typography: {
        fontFamily: 'Poppins',
        headingSize: 'large',
        bodySize: 'medium',
        headingWeight: 'bold',
      },
      buttons: {
        style: 'square',
        shadow: 'large',
        animation: 'none',
        borderRadius: 8,
      },
      spacing: {
        blockGap: 'comfortable',
        pagePadding: 'medium',
        maxWidth: 'medium',
      },
      colors: {
        primary: '#10b981',
        secondary: '#f59e0b',
        text: '#ffffff',
        textMuted: '#9ca3af',
        background: '#111827',
        cardBackground: '#1f2937',
      },
    },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },

  {
    id: 'podcast-hub',
    version: 1,
    name: 'Podcast & Media Hub',
    description: 'Latest episodes, streaming links, audio/video embeds, and newsletter',
    category: 'media',
    thumbnailUrl: 'https://images.unsplash.com/photo-1590602847861-f357a9332bbc?w=400&auto=format&fit=crop&q=80',
    isPremium: false,
    isActive: true,
    tags: ['podcast', 'audio', 'video'],
    defaultBlocks: [
      {
        id: 'block_podcast_header',
        type: 'profile-header',
        schemaVersion: 1,
        order: 0,
        config: {
          imageUrl: 'https://images.unsplash.com/photo-1589903102055-46ff858a2d10?w=300&auto=format&fit=crop&q=80',
          title: 'The Deep Dive Podcast',
          subtitle: 'Unfiltered conversations on technology, philosophy & high performance.',
          variant: 'centered',
          alignment: 'center',
          showVerifiedBadge: true,
        },
        isVisible: true,
      },
      {
        id: 'block_video_1',
        type: 'video-embed',
        schemaVersion: 1,
        order: 1,
        config: {
          videoUrl: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
          aspectRatio: '16:9',
          autoplay: false,
          title: '🎙️ Episode #84: Building Billion Dollar Protocols',
        },
        isVisible: true,
      },
      {
        id: 'block_spotify_link',
        type: 'link-button',
        schemaVersion: 1,
        order: 2,
        config: {
          text: 'Listen on Spotify',
          subtitle: 'Ranked #1 in Tech on Spotify Charts',
          url: 'https://spotify.com',
          variant: 'solid',
          color: '#1DB954',
          textColor: '#ffffff',
          icon: 'Music',
          animation: 'none',
          openInNewTab: true,
        },
        isVisible: true,
      },
      {
        id: 'block_apple_link',
        type: 'link-button',
        schemaVersion: 1,
        order: 3,
        config: {
          text: 'Listen on Apple Podcasts',
          subtitle: 'Rate & review our show on Apple',
          url: 'https://podcasts.apple.com',
          variant: 'solid',
          color: '#a855f7',
          textColor: '#ffffff',
          icon: 'Radio',
          animation: 'none',
          openInNewTab: true,
        },
        isVisible: true,
      },
    ],
    defaultTheme: {
      background: {
        type: 'gradient',
        gradient: {
          colors: ['#18181b', '#27272a', '#09090b'],
          angle: 180,
          type: 'linear',
        },
      },
      typography: {
        fontFamily: 'Inter',
        headingSize: 'medium',
        bodySize: 'medium',
        headingWeight: 'bold',
      },
      buttons: {
        style: 'pill',
        shadow: 'medium',
        animation: 'none',
        borderRadius: 9999,
      },
      spacing: {
        blockGap: 'comfortable',
        pagePadding: 'medium',
        maxWidth: 'medium',
      },
      colors: {
        primary: '#1DB954',
        secondary: '#a855f7',
        text: '#fafafa',
        textMuted: '#a1a1aa',
        background: '#09090b',
        cardBackground: 'rgba(39, 39, 42, 0.6)',
      },
    },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },

  {
    id: 'blank-canvas',
    version: 1,
    name: 'Blank Canvas (Start from Scratch)',
    description: 'Empty page ready for custom blocks and bespoke branding',
    category: 'general',
    thumbnailUrl: 'https://images.unsplash.com/photo-1557683316-973673baf926?w=400&auto=format&fit=crop&q=80',
    isPremium: false,
    isActive: true,
    tags: ['blank', 'custom', 'power-user'],
    defaultBlocks: [
      {
        id: 'block_blank_header',
        type: 'profile-header',
        schemaVersion: 1,
        order: 0,
        config: {
          imageUrl: '',
          title: 'My Profile',
          subtitle: 'Welcome to my official links!',
          variant: 'centered',
          alignment: 'center',
          showVerifiedBadge: false,
        },
        isVisible: true,
      },
    ],
    defaultTheme: {
      background: {
        type: 'solid',
        color: '#0f172a',
      },
      typography: {
        fontFamily: 'Inter',
        headingSize: 'medium',
        bodySize: 'medium',
        headingWeight: 'bold',
      },
      buttons: {
        style: 'rounded',
        shadow: 'medium',
        animation: 'none',
        borderRadius: 12,
      },
      spacing: {
        blockGap: 'comfortable',
        pagePadding: 'medium',
        maxWidth: 'medium',
      },
      colors: {
        primary: '#3b82f6',
        secondary: '#6366f1',
        text: '#ffffff',
        textMuted: '#94a3b8',
        background: '#0f172a',
        cardBackground: '#1e293b',
      },
    },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];
