// ReelAdTemplates.js — 6 production-quality reel ad templates
// Each template defines a complete reelConfig that transforms
// how the ad card looks inside the Reels feed.
// Admin selects a template → all reel config fields update instantly.

export const REEL_TEMPLATES = [
  {
    id: "reel-dark-ghost",
    name: "Dark Ghost",
    category: "Premium",
    description: "Dark overlay, frosted glass CTA, white text — works on any media",
    preview: { accent: "#ffffff", bg: "#000000" },
    reelConfig: {
      ctaText: "Learn More",
      btnVariant: "ghost",
      btnBgColor: "rgba(255,255,255,0.1)",
      btnTextColor: "#ffffff",
      btnBorderColor: "rgba(255,255,255,0.3)",
      btnRadius: "md",
      reelDescription: "",
      showDescription: true,
      showAdvertiserBadge: true,
      overlayOpacity: 85,
      overlayColor: "#000000",
      btnLinkType: "ad_details",
      btnLink: "",
      templateId: "reel-dark-ghost",
    },
  },
  {
    id: "reel-white-fill",
    name: "White Fill",
    category: "Clean",
    description: "Bold white filled pill button, minimal text, clean and sharp",
    preview: { accent: "#000000", bg: "#111111" },
    reelConfig: {
      ctaText: "Visit Now",
      btnVariant: "filled",
      btnBgColor: "#ffffff",
      btnTextColor: "#000000",
      btnBorderColor: "#ffffff",
      btnRadius: "full",
      reelDescription: "",
      showDescription: false,
      showAdvertiserBadge: true,
      overlayOpacity: 80,
      overlayColor: "#000000",
      btnLinkType: "ad_details",
      btnLink: "",
      templateId: "reel-white-fill",
    },
  },
  {
    id: "reel-outline-glow",
    name: "Outline Glow",
    category: "Bold",
    description: "White outline pill, deep overlay, high contrast for vibrant media",
    preview: { accent: "#ffffff", bg: "#050510" },
    reelConfig: {
      ctaText: "Explore Now",
      btnVariant: "outline",
      btnBgColor: "transparent",
      btnTextColor: "#ffffff",
      btnBorderColor: "#ffffff",
      btnRadius: "full",
      reelDescription: "",
      showDescription: true,
      showAdvertiserBadge: true,
      overlayOpacity: 90,
      overlayColor: "#050510",
      btnLinkType: "ad_details",
      btnLink: "",
      templateId: "reel-outline-glow",
    },
  },
  {
    id: "reel-amber-cta",
    name: "Amber CTA",
    category: "Bold",
    description: "Warm amber filled button, deep warm overlay — great for offers",
    preview: { accent: "#f59e0b", bg: "#1a0a00" },
    reelConfig: {
      ctaText: "Get Offer",
      btnVariant: "filled",
      btnBgColor: "#f59e0b",
      btnTextColor: "#000000",
      btnBorderColor: "#f59e0b",
      btnRadius: "lg",
      reelDescription: "",
      showDescription: true,
      showAdvertiserBadge: true,
      overlayOpacity: 82,
      overlayColor: "#1a0a00",
      btnLinkType: "external",
      btnLink: "",
      templateId: "reel-amber-cta",
    },
  },
  {
    id: "reel-indigo-brand",
    name: "Indigo Brand",
    category: "Premium",
    description: "Indigo filled button, deep overlay — professional brand feel",
    preview: { accent: "#6366f1", bg: "#06000f" },
    reelConfig: {
      ctaText: "Shop Now",
      btnVariant: "filled",
      btnBgColor: "#6366f1",
      btnTextColor: "#ffffff",
      btnBorderColor: "#6366f1",
      btnRadius: "md",
      reelDescription: "",
      showDescription: false,
      showAdvertiserBadge: true,
      overlayOpacity: 88,
      overlayColor: "#06000f",
      btnLinkType: "ad_details",
      btnLink: "",
      templateId: "reel-indigo-brand",
    },
  },
  {
    id: "reel-minimal",
    name: "Minimal",
    category: "Clean",
    description: "Lightest overlay, subtle ghost button — lets the media shine",
    preview: { accent: "#a1a1aa", bg: "#000000" },
    reelConfig: {
      ctaText: "Learn More",
      btnVariant: "ghost",
      btnBgColor: "rgba(0,0,0,0.3)",
      btnTextColor: "#ffffff",
      btnBorderColor: "rgba(255,255,255,0.15)",
      btnRadius: "sm",
      reelDescription: "",
      showDescription: true,
      showAdvertiserBadge: false,
      overlayOpacity: 60,
      overlayColor: "#000000",
      btnLinkType: "ad_details",
      btnLink: "",
      templateId: "reel-minimal",
    },
  },
];

export const REEL_TEMPLATE_CATEGORIES = {
  "All":     { bg: "rgba(99,102,241,0.15)",  color: "#818cf8", border: "#6366f1" },
  "Premium": { bg: "rgba(217,119,6,0.15)",   color: "#fbbf24", border: "#d97706" },
  "Bold":    { bg: "rgba(239,68,68,0.15)",   color: "#f87171", border: "#ef4444" },
  "Clean":   { bg: "rgba(16,185,129,0.15)",  color: "#34d399", border: "#10b981" },
};